### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by Mcat12** [nathanielsimard/mock-it#8]
Is there a changelog available? If not, can one be made?

**Comment by nathanielsimard** [comment]
Yes, it is now available [here](https://crates.io/crates/mock-it) as version `0.3.0`.

**Comment by Mcat12** [comment]
@nathanielsimard I do not see a changelog on that page or in the repository. Do you have a more direct link?

**Comment by nathanielsimard** [comment]
Ho sorry I read way to fast, I only did a release. I will create a changelog soon

**Comment by nathanielsimard** [comment]
I used Github releases to keep track of all changes : https://github.com/nathanielsimard/mock-it/releases
